### ISSUE TITLE
Colors in adtjes list do not have any clear meaning in their current state.

### ISSUE THREAD

**Issue by milo526** [BrakInBadjas/BibzSite#72]
We should change the colors of the timeline icons.
In their current way (green (success) for `open`, blue (primary) for` collected`) they do not convey a clear meaning for outsiders.

Since we currently do not support not-approved adtjes to be in the timeline, I think that we should use the [bootstrap contextual color](http://getbootstrap.com/css/#helper-classes-colors) `default` to convey the default status of `open`.  

There is some debate possible as to the color of the collected adtjes.  
They could be blue cause the primary action for an adtje is to collect it (and this color would match the `Adtje innen` knop).  
On the other side the green success color would make clear that you successfully "finished" the adtje by collecting it.

**Comment by jellemaas** [comment]
Green would be a better color for succes, because it is always green for succes. You could also make green for succes and orange for in progress needs allowed or denied and red when it is denied.

**Comment by cwitteveen** [comment]
Adtjes which are not approved yet are not shown in the page, neither are adtjes which are denied. They don't really need a color unless we change this

**Comment by xArcee** [comment]
I think it might be a good idea to also show these adtjes, Since they sort of end up in the void when you approve/not approve an adtje and there are not yet enough votes on it. I also agree with @jellemaas to use traffic light colors since everyone probably knows what these mean.
