### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by milo526** [BrakInBadjas/BibzSite#82]
## Internationalisation

I would like localise the site, laravel has build-in [localization](https://laravel.com/docs/5.4/localization) support.
I think adding i18n in the current state is already a big job but pushing it back even more will result in a high bug risk and even more work.
Updating the site now to support i18n will make the site more future proof for if and when we choose to give out accounts to non(-native) dutch speakers.
It would also fix some issues we are currently facing where some UI elements are in dutch and others are in English.

### Proposal
I propose changing the current views (not models) to let them accept Dutch and English translations.
I do not believe it is worth it in the current state to update the models (since most texts will lose there meaning or message).

We could add a column to the user account in which they can enter their preferred language, I think that, since the site and #Bibz itself are (where) originally dutch, dutch should be the default language.

### Side effects and upgradability
If we do choose to update the current site all views have to be updated and all new views after this will have to implement it before they will be merged to the dev and master branch.

**Comment by cwitteveen** [comment]
I think this is a good idea, escpecially if we want to be a do-group (We still need to discuss this i think).
