### ISSUE TITLE
Drinking buddies

### ISSUE THREAD

**Issue by cwitteveen** [BrakInBadjas/BibzSite#9]
some people just wanna watch everyone get wasted

**Comment by xArcee** [comment]
+1

**Comment by cwitteveen** [comment]
please keep issues serious @daniquel

**Comment by xArcee** [comment]
please keep issue descriptions serious @cwitteveen

**Comment by cwitteveen** [comment]
PHP
Composer
Laravel
Nodejs
Npm

Wamp als eventuele test omgeving
